### ISSUE TITLE
Paginator and Tags: conflict (sometimes)

### ISSUE THREAD

**Issue by ghost** [Stijn-Flipper/philePaginator#1]
Greetings!

When using both this wonderful Paginator and PhileTags (https://github.com/pschmitt/phileTags), there's problem when tag-words contain non-english alphabet letters or white spaces.

Why I post it here?

Because it's **Paginator** plug-in that throws an exception. Top of the stack is:

`7 sprintf(string,  integer)`
`/lager/webapps/koris.phile/plugins/stijnFlipper/philePaginator/Classes/Plugin.php:`

`00138:         $vars['paginator'] = array(`
`00139:             'offset'   => $this->offset,`
`00140:             'previous' => ($this->offset > 0) ? sprintf($uri, $this->offset - 1) : '',`
**`00141:             'next'     => ($this->offset < $max_pages) ? sprintf($uri, $this->offset + 1) : '',`**
`00142:             'pages'    => $this->getPages(),`
`00143:         );`
`00144:         \Phile\Registry::set($registry, $vars);`

The weird thing is, articles with such _problematic_ tags **do** appear on the page (right below error stack). I can send you an entire saved and zipped page if necessary for clarification of the problem.

Please, bear in mind that I'm not a PHP developer. Phile CMS is my first encounter with PHP source code so it might be that I'm missing something obvious.

So, what's the solution of problem I described?

**Comment by STOWouters** [comment]
Well, it's actually not related to the phileTags plugin. It's an uri encoding/decoding issue. For example, when requesting uri

```
/tag/äåé
```

the uri becomes

```
%2Ftag%2F%C3%A4%C3%A5%C3%A9
```

In combination with the `sprintf` there's the weird exception. I think I've fixed it now (quick tested it -- it's almost bedtime for me now ;) ). Can you confirm if it's fixed?

```
$ composer update
```

**Comment by ghost** [comment]
Works like a charm.
Thanks! ;-)
