### ISSUE TITLE
Prev button behaviour

### ISSUE THREAD

**Issue by ghost** [Stijn-Flipper/philePaginator#3]
Greetings again!

Well, this is most probably **not** a bug, but me missing something. For some reason, Prev link on your pager in my web site always points to site root (local address http://koris.phile). Querystring parameter `/?page=<some_number>` never gets attached to that link's `a` tag, I can see that in browser status bar.

Paging with Next link works as expected. Manual paging via hand-typing URI in addres bar also works, including http://koris.phile/?page=0

My directory structure is:
/content
--->index.html (this is blog page!)
--->(some other pages)
--->/blog
------>(blog posts)

I'm using nginx. _(Routing issue?)_

Everything is fine except that strange Prev link issue. What am I doing wrong? 

Temporarily, I crudely hacked that link's behaviour with `<a href="javascript: window.history.go(-1)">` but I'm not happy with it...

And one more question: Is there any way of using your paginator with phileTags plug-in (https://github.com/pschmitt/phileTags) so that one can paginate through tagged pages?

Best regards and than you for your time!

**Comment by STOWouters** [comment]
Well, as you said, this is _not_ a bug indeed, it's a feature :) If there's no previous page, then the `paginator.previous` is an empty string. Same goes if there's no next page. I use this in my blog (which also runs on nginx btw) to disable the button:

```
{% if paginator.previous is empty %}
{# disable the button #}
{% else %}
{# do not disable the button #}
{% endif %}
```

I'll update the README, so this issue is mentioned.

> And one more question: Is there any way of using your paginator with phileTags plug-in (https://github.com/pschmitt/phileTags) so that one can paginate through tagged pages?

There's no integration with the phileTags plugin (yet), my blog's also using tags, but it points to nothing, so I'll create an issue for that.

**Comment by bricebou** [comment]
Hum, I was going to open a new issue :  I have a strange behaviour too with the previous page... I've just understand: there is an error in the README. It's not 

```
paginator.prev
```

but

```
paginator.previous
```

**Comment by STOWouters** [comment]
Thanks for pointing that out, I'll update the README.
