### ISSUE TITLE
Define start page ?

### ISSUE THREAD

**Issue by bricebou** [Stijn-Flipper/philePaginator#5]
Hi,

I was wondering if there was a way to use as a config variable the start page number: for example, here is how looks my pagination: http://momh.fr/Phile/

So I try to add in the plugin config file:

```
'first_page' => 1,
```

Then in the Classes/Plugin.php, I try to add $this->settings['first_page'] to the $max_pages variable then to the $vars['paginator'] array but it seems that the first page of the paginated pages is still the 0.

Do you have any idea on how to achieve that ?

Thanks

**Comment by STOWouters** [comment]
So do you want `page=1` refers to the first page (which is currently `paginators.pages[0]`)? Or do you just want to display the pagination on your web as:

```
1 2 3 4 ..
```

For the last one, you can add a 1 in your Twig for-loop:

``` twig
{% for i in (paginator.offset + 1)..(paginator.pages | length) %}
{{ i }}
{% endfor %}
```

**Comment by bricebou** [comment]
For the last one, I tried with 

```
{% for i in 1..paginator.pages|length %}
```

but I find it strange to have a "1" button that refers to page 0, a 2 for 1...

Ideally, it would be nice to have the first paginated page to be 1, so `paginators.pages[1]` ; even better would be to have the ability to choose in the configuration.

Thanks.

**Comment by STOWouters** [comment]
> but I find it strange to have a "1" button that refers to page 0, a 2 for 1...

That's because of [fact #5 computer programmers know that most people don't](http://macleodsawyer.com/2015/03/06/nine-truths-computer-programmers-know-that-most-people-dont/#fact5) :)

> Ideally, it would be nice to have the first paginated page to be 1, so paginators.pages[1] ; even better would be to have the ability to choose in the configuration.

For me, it's ideally that the first paginated page to be 0, that's why we have a configuration file :) I think it's worth to add this to the configuration file, indeed.

**Comment by STOWouters** [comment]
Alright, you can now apply

```
$ composer update
```

And set `first_page` to `1` if you want to. It works on my side, so if you can confirm this, then you can close this issue.

**Comment by bricebou** [comment]
Hi,

It works perfectly locally and on my shared hosting ; for example : http://momh.fr/Phile/?page=2

Here is the code I'm using in my template:

```
<ul>
                        <li {{ paginator.previous is empty ? 'class="noprevnext"' : '' }}>
                            <a id="prev_page_link" title="Plus récents" href="{{ base_url }}/{{ paginator.previous }}">
                                <i class="fa fa-clock-o"></i><i class="fa fa-angle-right"></i>
                            </a>
                        </li>

                        {% for i in 0..paginator.pages|length -1 %}
                            {% if i == paginator.offset %}
                                <li class="pi pi_a"><a href="{{ base_url }}/?page={{ i+1 }}" class="page_item page_active"><i class="fa fa-clock-o"></i><span>{{ i+1 }}</span></a></li>
                            {% else %}
                                <li class="pi"><a href="{{ base_url }}/?page={{ i+1 }}" class="page_item">{{ i+1 }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <li {{ paginator.next is empty ? 'class="noprevnext"' : '' }}><a id="next_page_link" title="Plus anciens" href="{{ base_url }}/{{ paginator.next }}"><i class="fa fa-angle-left"></i><i class="fa fa-clock-o"></i></a></li>
                    </ul>
```

Thanks again :)

**Comment by STOWouters** [comment]
you're welcome :)

(nice blog btw :+1: )
