### ISSUE TITLE
Array_filter() expects parameter 1 to be array, object given

### ISSUE THREAD

**Issue by nlile** [Stijn-Flipper/philePaginator#8]
Added this plugin to my theme and get an error on every page except for the home. I switched to the default theme with default content as well and still got the same error.

```
array_filter() expects parameter 1 to be array, object given [2] 
triggered in file \plugins\stijnFlipper\philePaginator\Classes\Plugin.php on line 114 .
```

**Comment by westongpt** [comment]
in plugin.php change like 114 to read 

`$pages = array_filter($repo->findAll()->toArray(), $filter);`

that fixed it for me.

apparently at some point findAll stopped returning an array and instead returns a PageCollection

**Comment by nlile** [comment]
@Kronusdark sorry for such a late response. I created a different pagination system for the project I was working on last month, but I'm going to use your solution for a new project, so your solution isn't going to waste :) -- Thanks for the solution!
